### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by jnsl** [aebrahim/pidgin-wincred#1]
Can you provide newer binaries? I only see 0.4 on the deprecated google code site.
thx

**Comment by aebrahim** [comment]
Do the ones on the releases page work? There should be a version 0.5 there.

https://github.com/aebrahim/pidgin-wincred/releases

**Comment by jnsl** [comment]
The only place i did not look. m)
A link in the readme.md would be good, i guess.
Issue is resolved otherwise. ;) Thx!

**Comment by aebrahim** [comment]
Good idea. Added the link
